[versions]
# Plugins
android-gradle = "8.1.1"
google-services = "4.3.15"
junit5-android = "1.9.3.0"
kotlin = "1.9.10"
versions = "0.48.0"
versions-catalog-update = "0.8.1"
# AndroidX
androidx-appCompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-coreKtx = "1.7.0"
androidx-lifecycle = "2.6.2"
androidx-navigation = "2.6.0"
androidx-paging = "3.2.1"
androidx-swiperefreshlayout = "1.1.0"
# Coroutines
coroutines = "1.7.3"
# General
dagger = "2.48"
firebase-analytics = "21.3.0"
firestore = "24.7.1"
glide = "4.16.0"
material = "1.9.0"
# Testing
junit5 = "5.8.2"
mockito-kotlin = "5.1.0"
turbine = "1.0.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
androidx-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
junit5-android = { id = "de.mannodermaus.android-junit5", version.ref = "junit5-android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
versions-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versions-catalog-update" }

[libraries]
# AndroidX
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKtx" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-paging = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
# Coroutines
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
# General
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firestore = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firestore" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
material = { module = "com.google.android.material:material", version.ref = "material" }
# Testing
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
